# Generated by Django 5.2.11 on 2026-02-04 01:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.CharField(blank=True, help_text='Internal employee identifier (optional).', max_length=50, verbose_name='employee ID')),
                ('employee_number', models.CharField(blank=True, help_text='Employee number used in payroll exports (optional).', max_length=50, verbose_name='employee number')),
                ('initials', models.CharField(blank=True, help_text='Unique initials used in partner reporting.', max_length=10, unique=True, verbose_name='initials')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='job title')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='department')),
                ('active', models.BooleanField(default=True, help_text='Whether the employee is active for reporting.', verbose_name='active')),
                ('seniority_order', models.PositiveIntegerField(default=999, help_text='Lower number = more senior. Used for sorting reports.', verbose_name='seniority order')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='hire date')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='termination date')),
                ('is_exempt', models.BooleanField(default=True, help_text='Whether the employee is exempt from overtime rules.', verbose_name='exempt employee')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone number')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('mileage_rate', models.DecimalField(decimal_places=3, default=0.67, help_text='IRS standard mileage rate for reimbursement.', max_digits=5, verbose_name='mileage rate ($/mile)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'employee profile',
                'verbose_name_plural': 'employee profiles',
                'ordering': ['seniority_order', 'user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeProfile',
            fields=[
                ('employee_id', models.CharField(blank=True, help_text='Internal employee identifier (optional).', max_length=50, verbose_name='employee ID')),
                ('employee_number', models.CharField(blank=True, help_text='Employee number used in payroll exports (optional).', max_length=50, verbose_name='employee number')),
                ('initials', models.CharField(blank=True, db_index=True, help_text='Unique initials used in partner reporting.', max_length=10, verbose_name='initials')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='job title')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='department')),
                ('active', models.BooleanField(default=True, help_text='Whether the employee is active for reporting.', verbose_name='active')),
                ('seniority_order', models.PositiveIntegerField(default=999, help_text='Lower number = more senior. Used for sorting reports.', verbose_name='seniority order')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='hire date')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='termination date')),
                ('is_exempt', models.BooleanField(default=True, help_text='Whether the employee is exempt from overtime rules.', verbose_name='exempt employee')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone number')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('mileage_rate', models.DecimalField(decimal_places=3, default=0.67, help_text='IRS standard mileage rate for reimbursement.', max_digits=5, verbose_name='mileage rate ($/mile)')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee profile',
                'verbose_name_plural': 'historical employee profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('date_joined', models.DateTimeField(blank=True, editable=False, verbose_name='date joined')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user',
                'verbose_name_plural': 'historical users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
